// MANOHAR MOBILE SHOP - CLOUD + UPI CONFIG
window.APP_CONFIG = {
  SUPABASE_URL: "YOUR_SUPABASE_PROJECT_URL",
  SUPABASE_ANON_KEY: "YOUR_SUPABASE_PUBLISHABLE_OR_ANON_KEY",
  UPI_ID: "YOUR-UPI-ID@BANK",
  UPI_NAME: "MANOHAR MOBILE SHOP",
  UPI_QR_IMAGE: "qr/upi-qr.png"
};
